services:
  db:
    image: postgres
    user: postgres
    volumes:
      - plank-db-data:/var/lib/postgresql/data
    networks:
      - webnet
    secrets:
      - plank-db-password
    environment:
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD_FILE=/run/secrets/plank-db-password
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: ghcr.io/blakexyz/webapp-walk-the-plank-ghcr:${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.plank-web.loadbalancer.server.port=5000"
      - "traefik.http.routers.plank-web.rule=Host(`walktheplank.app`)"
      - "traefik.http.routers.plank-web.entrypoints=websecure"
      - "traefik.http.routers.plank-web.tls.certresolver=myresolver"
    networks: 
      - webnet
    secrets:
      - plank-db-password
    environment:
      - POSTGRES_HOST=plank-stack_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/plank-db-password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
      - FLASK_ENV=production
      - SECRET_KEY=your-very-secret-key
      - SEND_FILE_MAX_AGE_DEFAULT=31556926
      - BCRYPT_LOG_ROUNDS=13
      - FLASK_DEBUG=0
      - LOG_LEVEL=info
      - GUNICORN_WORKERS=1
      - SOCKET_CORS_ORIGINS=https://walktheplank.app,https://www.walktheplank.app
    deploy:
      update_config:
        order: start-first
    depends_on:
      - db

  # #connect to: http://{ip_address}:8081
  # to remove, run: - docker service rm ham-stack-deploy_pgadmin
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=artificialblakek@gmail.com
  #   secrets:
  #     - pgadmin-password
  #   entrypoint: ["/bin/sh", "-c", "export PGADMIN_DEFAULT_PASSWORD=$$(cat /run/secrets/pgadmin-password) && exec /entrypoint.sh"]
  #   depends_on:
  #     - web
  #   ports:
  #     - "8081:80"
  #   networks:
  #     - webnet

volumes:
  plank-db-data:

secrets:
  plank-db-password:
    external: true
  pgadmin-password:
    external: true

networks:
  webnet:
    external: true # References the shared network created by the Traefik stack
    name: traefik-deploy_webnet  #  {stack name}_{network name}